name: Build and deploy Docker app to Azure

on: push

env:
  AZURE_WEBAPP_NAME: tuomokar-spacex
  CONTAINER_REGISTRY: ${{ secrets.REGISTRY_URL }}

jobs:
  build-and-deploy-to-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Azure authentication
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: ACR authentication
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.CONTAINER_REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}    
    - name: Docker Build & Push to ACR
      run: |
        docker build --shm-size 1G . -t ${{ env.CONTAINER_REGISTRY }}/spacex1:${{ github.sha }}
        docker push ${{ env.CONTAINER_REGISTRY }}/spacex1:${{ github.sha }} 
    - name: 'Deploy to Azure Web App for Container'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }} 
        images: ${{ env.CONTAINER_REGISTRY }}/spacex1:${{ github.sha }}
